# Generated by Django 2.2.4 on 2019-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='imageurl',
            field=models.URLField(default='empty'),
            preserve_default=False,
        ),
    ]
