# Generated by Django 2.2.4 on 2019-09-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_auto_20190902_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageurl',
            name='imgtask_id',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
